[enforcer]
debug = false

[snmp]
snmpCommunity = "public"
snmpOID = ".1.3.6.1.4.1.2636.13.61.1.9.1.1.1"
snmpLogsOID = ".1.3.6.1.4.1.2636.13.61.1.9.1.1.2"
snmpWalkableOID = ".1.3.6.1.4.1.2636.13.61.1.9.1.1.3"

[http]
port = "3000"
uipath = "../webui"
# address = "127.0.0.1"
address = "0.0.0.0"